trailingComma = "es5"
semi = true
singleQuote = true
plugins = ["@trivago/prettier-plugin-sort-imports"]
importOrder = ["^@", "^components|^./components", "assets|contexts", "^./pages", "^[./]"]
importOrderSeparation = true
importOrderSortSpecifiers = true
